import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Enterprise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-6xl">Next.js Enterprise</h1>
      <p>This project is powered by `next-auth` and WorkOS</p>
    </div>
  );
};

export default Home;
